# Generated by Django 6.0.6 on 2026-06-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.PositiveIntegerField(default=0, verbose_name='Очки Команды 1')),
                ('score_2', models.PositiveIntegerField(default=0, verbose_name='Очки Команды 2')),
                ('date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Матч завершен?')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='Был овертайм?')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube (Обзор/Матч)')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на TikTok')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название команды')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams_logos/', verbose_name='Логотип команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='MatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='match_photos/', verbose_name='Фотография')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tournament.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Фото с матча',
                'verbose_name_plural': 'Фотографии с матчей',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='players_avatars/', verbose_name='Аватарка')),
                ('category', models.CharField(choices=[('PRO', 'Профи'), ('MEDIA', 'Медиа'), ('AMATEUR', 'Любитель')], max_length=10, verbose_name='Категория')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе / Инфо')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournament.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team', verbose_name='Команда 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team', verbose_name='Команда 2'),
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Набранные очки')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Ассисты')),
                ('fouls', models.PositiveIntegerField(default=0, verbose_name='Фолы')),
                ('four_pointers', models.PositiveIntegerField(default=0, verbose_name='Попадания из 4-очковой зоны')),
                ('bullet_points', models.PositiveIntegerField(default=0, verbose_name='Очки с буллитов')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournament.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='tournament.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Статистика игрока за матч',
                'verbose_name_plural': 'Статистика игроков за матчи',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
