# Generated by Django 6.0.6 on 2026-06-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playermatchstat',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playermatchstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.IntegerField(default=0, verbose_name='Очки Команды 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_2',
            field=models.IntegerField(default=0, verbose_name='Очки Команды 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Аватар игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Логотип команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название команды'),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Набранные очки')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournament.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tournament.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Статистика игрока в матче',
                'verbose_name_plural': 'Статистика игроков в матчах',
            },
        ),
        migrations.DeleteModel(
            name='MatchPhoto',
        ),
        migrations.DeleteModel(
            name='PlayerMatchStat',
        ),
    ]
