# Generated by Django 6.0.6 on 2026-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_playermatchstat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('pro', 'Профи'), ('media', 'Медиа'), ('amateur', 'Любитель')], default='amateur', max_length=10, verbose_name='Категория игрока'),
        ),
    ]
