# Generated by Django 6.0.6 on 2026-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_player_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки Команды 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки Команды 2'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Набранные очки'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название команды'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('match', 'player')},
        ),
    ]
