# Generated by Django 6.0.6 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм (Игровое имя)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Очки Команны 1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('PRO', 'Профи'), ('MEDIA', 'Медиа'), ('AMATEUR', 'Любитель')], default='AMATEUR', max_length=10, verbose_name='Категория игрока'),
        ),
    ]
