# Generated by Django 6.0.6 on 2026-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_player_nickname_alter_match_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AddField(
            model_name='player',
            name='leading_hand',
            field=models.CharField(choices=[('Правая', 'Правая'), ('Левая', 'Левая')], default='Правая', max_length=20, verbose_name='Ведущая рука'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='Атакующий защитник', max_length=100, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
    ]
